# Generated by Django 3.2.6 on 2022-10-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='email',
        ),
    ]
