# Generated by Django 3.2.6 on 2022-10-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_sign_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='email',
            field=models.EmailField(default='', max_length=10),
        ),
    ]
