# Generated by Django 3.2.6 on 2022-10-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_sign_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
