# Generated by Django 5.2.4 on 2025-09-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='username',
            new_name='name',
        ),
        migrations.AddField(
            model_name='sign',
            name='department',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sign',
            name='perm_id',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='sign',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
