# Generated by Django 5.2.4 on 2025-09-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_username_sign_name_sign_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
