# Generated by Django 5.2.4 on 2025-09-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_sign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
