# Generated by Django 5.2.4 on 2025-09-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_sign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
